- name: Install Apache2
  apt:
    name: '{{ item.name }}'
    state: present
    update_cache: yes
  with_items:
    - name: apache2
    - name: libapache2-mod-proxy-uwsgi

- name: Start Apache2
  service:
    name: apache2
    state: started
    enabled: true

- name: Enable proxy module
  apache2_module:
    state: present
    name: '{{ item.name }}'
  with_items:
    - name: proxy
    - name: proxy_uwsgi

- name: Copy proxy.conf
  copy:
    src: proxy.conf
    dest: /etc/apache2/mods-enabled/proxy.conf
  notify: restart apache2
